### Importing Warnings

In [10]:
import warnings
warnings.filterwarnings('ignore')


### Importing Packages




In [11]:
import pandas as pd
import numpy as np

### Importing Dataset Using Pandas

In [12]:
data=pd.read_csv('twitter-stocks.csv')

### Know dataset Structure

In [13]:
data.shape

(2259, 7)

### Know columns


In [14]:
data.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

### Let's see all rows 

In [15]:
pd.options.display.max_rows=5000
data.head(2259)

Date       Open       High        Low      Close  Adj Close  \
0     2013-11-07  45.099998  50.090000  44.000000  44.900002  44.900002   
1     2013-11-08  45.930000  46.939999  40.685001  41.650002  41.650002   
2     2013-11-11  40.500000  43.000000  39.400002  42.900002  42.900002   
3     2013-11-12  43.660000  43.779999  41.830002  41.900002  41.900002   
4     2013-11-13  41.029999  42.869999  40.759998  42.599998  42.599998   
5     2013-11-14  42.340000  45.669998  42.240002  44.689999  44.689999   
6     2013-11-15  45.250000  45.270000  43.430000  43.980000  43.980000   
7     2013-11-18  43.500000  43.950001  40.849998  41.139999  41.139999   
8     2013-11-19  41.389999  41.900002  40.000000  41.750000  41.750000   
9     2013-11-20  41.400002  41.750000  40.509998  41.049999  41.049999   
10    2013-11-21  41.250000  42.490002  40.369999  42.060001  42.060001   
11    2013-11-22  41.810001  42.279999  40.970001  41.000000  41.000000   
12    2013-11-25  41.080002  41.139999  38.799999  39.060001  39.060001   
13    2013-11-26  39.160000  40.549999  38.919998  40.180000  40.180000   
14    2013-11-27  40.470001  41.400002  40.349998  40.900002  40.900002   
15    2013-11-29  41.400002  41.580002  40.900002  41.570000  41.570000   
16    2013-12-02  41.790001  42.000000  40.400002  40.779999  40.779999   
17    2013-12-03  40.689999  41.599998  40.540001  41.369999  41.369999   
18    2013-12-04  41.270000  43.919998  41.270000  43.689999  43.689999   
19    2013-12-05  43.450001  46.349998  42.830002  45.619999  45.619999   
20    2013-12-06  45.750000  45.799999  44.540001  44.950001  44.950001   
21    2013-12-09  45.590000  49.840000  45.020000  49.139999  49.139999   
22    2013-12-10  48.900002  52.580002  48.700001  51.990002  51.990002   
23    2013-12-11  52.400002  53.869999  51.000000  52.340000  52.340000   
24    2013-12-12  52.200001  55.869999  50.689999  55.330002  55.330002   
25    2013-12-13  56.200001  59.410000  55.450001  59.000000  59.000000   
26    2013-12-16  57.860001  60.240002  55.759998  56.610001  56.610001   
27    2013-12-17  56.970001  57.380001  54.619999  56.450001  56.450001   
28    2013-12-18  57.000000  57.000000  54.230000  55.509998  55.509998   
29    2013-12-19  55.080002  57.750000  55.000000  57.490002  57.490002   
30    2013-12-20  58.509998  60.250000  58.009998  60.009998  60.009998   
31    2013-12-23  59.849998  64.989998  59.700001  64.540001  64.540001   
32    2013-12-24  66.339996  70.870003  65.559998  69.959999  69.959999   
33    2013-12-26  72.879997  74.730003  69.130096  73.309998  73.309998   
34    2013-12-27  70.099998  71.250000  63.689999  63.750000  63.750000   
35    2013-12-30  60.270000  63.709999  58.570000  60.509998  60.509998   
36    2013-12-31  62.360001  65.220001  61.650002  63.650002  63.650002   
37    2014-01-02  65.000000  67.500000  64.400002  67.500000  67.500000   
38    2014-01-03  69.000000  70.430000  68.431999  69.000000  69.000000   
39    2014-01-06  64.830002  66.870003  63.500000  66.290001  66.290001   
40    2014-01-07  67.669998  67.730003  61.389999  61.459999  61.459999   
41    2014-01-08  58.709999  61.259998  57.919998  59.290001  59.290001   
42    2014-01-09  59.540001  60.810001  55.590000  57.049999  57.049999   
43    2014-01-10  57.500000  58.759998  55.869999  57.000000  57.000000   
44    2014-01-13  59.980000  60.380001  57.293999  57.820000  57.820000   
45    2014-01-14  58.880001  59.020000  57.360001  58.209999  58.209999   
46    2014-01-15  59.110001  61.750000  58.320000  61.570000  61.570000   
47    2014-01-16  61.450001  62.400002  60.459999  60.570000  60.570000   
48    2014-01-17  63.599998  64.690002  61.590000  62.200001  62.200001   
49    2014-01-21  63.330002  63.439999  61.500000  62.529999  62.529999   
50    2014-01-22  63.110001  63.799999  61.759998  62.439999  62.439999   
51    2014-01-23  61.450001  62.810001  60.880001  62.799999  62.799999   
52    2014-01-24  62.169998  63.61999

### Information regarding columns


In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2259 entries, 0 to 2258
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Date       2259 non-null   object 
 1   Open       2259 non-null   float64
 2   High       2259 non-null   float64
 3   Low        2259 non-null   float64
 4   Close      2259 non-null   float64
 5   Adj Close  2259 non-null   float64
 6   Volume     2259 non-null   float64
dtypes: float64(6), object(1)
memory usage: 123.7+ KB


### Let's Check Unique Values

#### Open Value

In [22]:
data['Open'].unique()

array([45.099998, 45.93    , 40.5     , ..., 52.415001, 52.950001,
       53.91    ])

#### High

In [23]:
data['High'].unique()

array([50.09    , 46.939999, 43.      , ..., 53.18    , 53.5     ,
       54.      ])

#### Low

In [24]:
data['Low'].unique()

array([44.      , 40.685001, 39.400002, ..., 50.52    , 52.200001,
       52.77    ])

#### Close

In [25]:
data['Close'].unique()

array([44.900002, 41.650002, 42.900002, ..., 51.52    , 52.779999,
       53.349998])

#### Adj Close

In [26]:
data['Adj Close'].unique()

array([44.900002, 41.650002, 42.900002, ..., 51.52    , 52.779999,
       53.349998])

#### Volume

In [27]:
data['Volume'].unique()

array([1.17701670e+08, 2.79253070e+07, 1.61139410e+07, ...,
       3.50778480e+07, 2.80649730e+07, 1.36345128e+08])

### Let's See Mean Mode Median And Quartiles Of Each Column

In [28]:
data.describe()

Open         High          Low        Close    Adj Close  \
count  2259.000000  2259.000000  2259.000000  2259.000000  2259.000000   
mean     36.020286    36.699881    35.339465    36.003625    36.003625   
std      14.118463    14.372057    13.828724    14.089989    14.089989   
min      13.950000    14.220000    13.725000    14.010000    14.010000   
25%      25.550000    26.215001    24.912501    25.410000    25.410000   
50%      35.419998    36.099998    34.820000    35.490002    35.490002   
75%      44.205000    45.015000    43.327501    44.135000    44.135000   
max      78.360001    80.750000    76.050003    77.629997    77.629997   

             Volume  
count  2.259000e+03  
mean   2.175186e+07  
std    1.909988e+07  
min    0.000000e+00  
25%    1.233530e+07  
50%    1.691305e+07  
75%    2.428082e+07  
max    2.692131e+08

### Let's See For Duplicates

In [30]:
data.duplicated().sum()   ### There Were No Duplicates

0

### Let's See Is There Any Null Values

In [34]:
data.isnull().sum()       #### There Were No Null Values

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64